# Generated by Django 4.0.4 on 2022-04-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_description', models.TextField()),
                ('department_id', models.IntegerField()),
                ('industry', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('cpassword', models.CharField(max_length=20)),
                ('phone_no', models.CharField(max_length=50)),
                ('card_no', models.IntegerField()),
                ('time', models.DateField(default='04/14/22')),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('hospital', models.CharField(max_length=45)),
                ('audit_no', models.IntegerField()),
                ('comments', models.TextField()),
                ('uploads', models.ImageField(upload_to=None)),
                ('date', models.DateField(default='04/14/22')),
                ('response_file', models.FileField(max_length=254, upload_to=None)),
                ('dept', models.CharField(max_length=200)),
            ],
        ),
    ]
