# Generated by Django 4.0.4 on 2022-05-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_description', models.TextField()),
                ('department_id', models.IntegerField()),
                ('industry', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('hospital', models.CharField(max_length=45)),
                ('audit_no', models.IntegerField()),
                ('comments', models.TextField()),
                ('uploads', models.ImageField(upload_to=None)),
                ('date', models.DateField(default='05/09/22')),
                ('response_file', models.FileField(max_length=254, upload_to=None)),
                ('dept', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuestionnaire',
            fields=[
                ('user_id', models.IntegerField()),
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_description', models.TextField()),
                ('department_id', models.IntegerField()),
                ('topic_id', models.IntegerField()),
            ],
        ),
    ]
