# Generated by Django 4.0.4 on 2022-04-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditplus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='card_no',
        ),
        migrations.RemoveField(
            model_name='register',
            name='cpassword',
        ),
        migrations.RemoveField(
            model_name='register',
            name='time',
        ),
        migrations.AlterField(
            model_name='responses',
            name='date',
            field=models.DateField(default='04/27/22'),
        ),
    ]
