# Generated by Django 4.0.4 on 2022-05-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditplus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='date',
            field=models.DateField(default='05/01/22'),
        ),
    ]
