# Generated by Django 4.0.4 on 2022-05-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditplus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSectors',
            fields=[
                ('sector_id', models.AutoField(primary_key=True, serialize=False)),
                ('sector_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='responses',
            name='date',
            field=models.DateField(default='05/10/22'),
        ),
    ]
