# Generated by Django 4.0.4 on 2022-04-27 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditplus', '0002_remove_register_card_no_remove_register_cpassword_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='username',
            new_name='email_id',
        ),
    ]
