# Generated by Django 4.0.4 on 2022-05-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditplus', '0002_alter_responses_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='date',
            field=models.DateField(default='05/02/22'),
        ),
    ]
