# Generated by Django 4.0.4 on 2022-04-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditplus', '0003_rename_username_register_email_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestionnaire',
            fields=[
                ('user_id', models.IntegerField()),
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_description', models.TextField()),
                ('department_id', models.IntegerField()),
                ('industry', models.CharField(max_length=40)),
            ],
        ),
    ]
