# Generated by Django 4.0.4 on 2022-05-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditplus', '0004_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='date',
            field=models.DateField(default='05/03/22'),
        ),
    ]
