# Generated by Django 4.0.4 on 2022-05-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditplus', '0005_alter_responses_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
